name: release

on:
  push:
    tags: ['v*']

jobs:
  zip-release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: zip
        run: |
          zip -r teams-ext.zip ./ -x '*.git*'

      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: teams-ext.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
